enabled_categories:
  type: list
  list_type: category
  default: ""
  description: "Choose which categories that users need to sign up for."
enabled_tags:
  type: list
  list_type: tag
  default: ""
  description: "Choose which tags that users need to sign up for. The default is 'gated'."
enabled_groups:
  type: list
  list_type: group
  default: "5"
  disallowed_groups: "4"
  resolve_group_membership: true
  description: "Choose which groups users need to be a member of to view the content when 'enable_gating_with_groups' is enabled."
enable_gating_with_groups:
  type: bool
  default: true
  description: "Enable gating with groups. If enabled, users must be a member of the specified groups to view the content."
group_custom_button_link:
  type: string
  default: ""
  description: "Optionally specify a custom URL for the call-to-action button for groups."
